//%attributes = {}
Begin SQL
	
	CREATE TABLE IF NOT EXISTS BOUTIQUE (
	
	ID INT32 AUTO_INCREMENT PRIMARY KEY,
	Nom VARCHAR NOT NULL,
	ID_EVENEMENT INT32
	);
	
End SQL

ALERT:C41("TABLE BOUTIQUE CREEE")