//%attributes = {}
Begin SQL
	
	ALTER TABLE BOUTIQUE
	ADD CONSTRAINT fk_idevenement
	FOREIGN KEY (ID_Evenement)
	REFERENCES EVENEMENT (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;
	
End SQL

ALERT:C41("CONTRAINTE INTEGRITE DONE")